### ISSUE TITLE
Add 'copy_field' functionality

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-filter-mutate#39] opened 2015-07-22 20:43 UTC
Currently to copy a field one must use `add_field` with a sprintf style statement. This is confusing to newbies and not semantically rich. I propose we add a `copy_field` statement that solves this.

**Comment by purbon** [comment] 2015-09-08 08:07
++ This makes complete sense to me, however I wonder why a user would like to copy a field? do you have a use case in mind?

**Comment by purbon** [comment] 2015-09-08 10:38
@andrewvc closing this as duplicate of #12

**Closed by purbon** 2015-09-08 10:38 UTC
Labels: enhancement, feature-request
