### ISSUE TITLE
Uppercase / Lowercase for Unicode

### ISSUE THREAD

**Issue by doubret** [logstash-plugins/logstash-filter-mutate#17] opened 2015-03-23 18:29 UTC
Please, add Unicode support (utf-8) for Uppercase and Lowercase. 

Thanks

**Comment by suyograo** [comment] 2015-04-14 19:09
There's a gem that supports unicode transformations. http://unicode-utils.rubyforge.org/

**Comment by Cidan** [comment] 2015-04-20 20:02
+1

**Comment by doubret** [comment] 2015-05-21 13:24
Is there any progress on this ?

**Comment by duylong** [comment] 2015-05-26 07:55
+1

Do you have a temporary solution ?

**Comment by doubret** [comment] 2015-05-26 08:37
I have a workaround that works for my use case but the best would be to use unicode gem.

Anyway, in my case my string is in unicode but it is compliant with ansi so i force string encoding before upcase/downcase like this (line 358 in mutate.rb) :

        event[field] = event[field].force_encoding("ISO-8859-1").downcase

Hope this helps.

**Comment by duylong** [comment] 2015-05-26 09:23
Thank you, it works ! (in waiting a clean solution).

Strangely, no problem with logstash 1.4.x and no change in "mutate" plugin.

**Comment by doubret** [comment] 2015-05-26 10:43
Strange, i had the same problem with logstash 1.4.

**Comment by duylong** [comment] 2015-05-26 12:10
I change codec "line" to "plain" with migration to 1.5. Maybe it changed the behavior of the encoding.

**Comment by suyograo** [comment] 2015-08-04 20:36
@guyboertje related to #33 probably

**Comment by guyboertje** [comment] 2015-08-05 09:17
@suyograo - yes probably.

**Comment by guyboertje** [comment] 2015-08-06 22:25
I can confirm this is a duplicate of #33 in terms of the cause and solution

**Closed by guyboertje** 2015-08-06 22:25 UTC
Labels: enhancement
