### ISSUE TITLE
Mutate filter lowercase and uppercase not working

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-mutate#33] opened 2015-05-18 06:22 UTC
(This issue was originally filed by @Hark82 at https://github.com/elastic/logstash/issues/2973)

---

logstash-1.5.0.rc2

Adding mutate filter lowercase or uppercase in the config has no effect.

**Comment by soichih** [comment] 2015-06-19 01:08
I am getting hit by this. Is there a workaround?

**Comment by melaniemj** [comment] 2015-06-29 17:20
+1

**Comment by utilitynerd** [comment] 2015-06-30 21:19
Also causing big problems for me, any timeline for a fix?

**Comment by ruria** [comment] 2015-07-10 15:45
thanks for this workaround! but this works better for me:

ruby {
code => "event['field'] = event['field'].to_s.force_encoding('ISO-8859-1').downcase"
}

**Comment by eperry** [comment] 2015-07-19 14:05
I ran into this same problem too, with the latest logstash download.  the Ruby workaround fixed it for me too.

**Comment by willemdh** [comment] 2015-08-04 09:16
Lowercase is also no longer working since upgrading to 1.5. (Gsub also does not seem to work anymore)

**Comment by guyboertje** [comment] 2015-08-04 10:44
@willemdh, @eperry, @ruria, @utilitynerd, @melaniemj, @soichih 
What OS are you using when you see this problem?

**Comment by willemdh** [comment] 2015-08-04 12:26
CentOS 6.6 here. (Gsub does work. As the lowercase didn't work, the fieldname in the gsub wasn't correct anymore.)

**Comment by jessebolson** [comment] 2015-08-04 14:44
@guyboertje 
I am experiencing the same issue, details below.

Linux localhost.localdomain 2.6.32-279.11.1.el6.x86_64 #1 SMP Tue Oct 16 15:57:10 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
CentOS release 6.6 (Final)
logstash 1.5.1

**Comment by guyboertje** [comment] 2015-08-04 19:50
This looks like a jruby bug.  Its fixed in jruby 9.0.0.0 - https://github.com/jruby/jruby/issues/2847

Please try setting the JRUBY_OPTS env var like so ```JRUBY_OPTS="-Ku"``` and report back.

**Comment by willemdh** [comment] 2015-08-05 12:23
Guy, I did some tests. One thing I noticed is that in some cases the lowercase does seem to work as expected (syslog input) The input where it doesn't work are Windows eventlog sent by NxLog with this input:
tcp {
    type => 'eventlog'
    port => 3515
    codec => json {
        charset => 'CP1252'
    }
}
It seems like the lowercase issue is only for json input. Maybe if someone else could confirm this.
I tried doing this on both CentOS 6.6 elk nodes:
    export JRUBY_OPTS="-Ku"
    service logstash restart

And reverted the ruby workaround to the mutate lowercase, but it sill does not seem to work.

**Comment by ruria** [comment] 2015-08-05 12:56
I confirm that. I think is a encoding (utf vs. ascii) issue.
--
Sent from myMail app for Android Wednesday, 05 August 2015, 02:23PM +02:00 from willemdh < notifications@github.com> :

**Comment by jsvd** [comment] 2015-08-05 16:30
here's a reproducible scenario that might help debugging:

Works on a simple message:

```
% echo 'hELoOoOo' | bin/logstash -e 'input { stdin { codec => plain } } filter { mutate { lowercase => "message" } } output { stdout { } }'
2015-08-05T16:27:53.114Z Joaos-MBP.lan helooooo
```

Fails on a JSON document:

```
 % echo '{"message":"hELoOoOo"}' | bin/logstash -e 'input { stdin { codec => json } } filter { mutate { lowercase => "message" } } output { stdout { } }'                   
2015-08-05T16:23:45.115Z Joaos-MBP.lan hELoOoOo
```

**Comment by ruria** [comment] 2015-08-06 15:10
CentOS 6.

**Comment by guyboertje** [comment] 2015-08-06 15:33
I have found the bug and the fix.  Expect Pull Request v shortly.

**Comment by willemdh** [comment] 2015-08-06 20:17
Thanks Guy!

**Comment by suyograo** [comment] 2015-08-11 23:04
@guyboertje any progress on this?

**Comment by jsvd** [comment] 2015-08-12 09:17
The PR Guy made is being reviewed https://github.com/logstash-plugins/logstash-filter-mutate/pull/42

**Comment by guyboertje** [comment] 2015-08-12 20:35
PR 43 opened - under review
PR 42 closed

**Closed** 2015-08-14 18:40 UTC
Labels: enhancement
